package com.example.aksa.dataMitos

import com.example.aksa.R

object DataMitos {
    val listMitos = listOf(
        Mitos(
            id = 1,
            name = "Situ Gede",
            img = R.drawable.situgede,
            desc = "Situ Gede di Tasikmalaya adalah sebuah danau yang menyimpan kisah misteri yang menyelimutinya. Meskipun kini menjadi lokasi wisata yang banyak dikunjungi, terutama di hari libur, cerita-cerita tentang Situ Gede tetap mengundang rasa ingin tahu. Asal Usul Situ Gede: Kisah yang berkembang di masyarakat tentang asal mula terbentuknya Situ Gede berkaitan erat dengan perjalanan hidup Eyang Prabudilaya. Eyang Prabudilaya, atau Prabu Adilaya, merupakan seorang Raja Muda Sumedang yang meninggal dibunuh oleh kedua istrinya. Ia kemudian dimakamkan di tanah rawa yang kini menjadi Situ Gede. Cerita dimulai ketika Prabu Adilaya belum melaksanakan kewajibannya kepada kedua istrinya. Fokusnya pada ilmu pengetahuan membuatnya kurang memperhatikan mereka. Kedua istrinya, Nyai Raden Dewi Kondang Hapa dan Dewi Cahya Karembong, merasa tidak bahagia sebagai istri. Akhirnya, keduanya sepakat untuk membunuh Prabu Adilaya. Kedua istrinya bersama pelayannya memakamkan Prabu Adilaya di sebuah rawa di daerah Tasikmalaya. Karena tidak ada kabar tentang anaknya, ibu Prabu Adilaya mencari sang anak hingga tiba di suatu tempat di wilayah Sukapura atau Tasikmalaya. Di sana, terbentuklah Situ Gede, dan di tengah situ ini terdapat sebuah pulau seluas satu hektar yang menjadi tempat makam Eyang Prabudilaya1. Mitos dan Misteri: Menurut mitos yang berkembang di sekitar Situ Gede, terdapat empat sosok ikan gaib yang menjaga danau tersebut. Ikan-ikan ini tidak hanya menampakkan diri pada orang yang memiliki niat buruk, tetapi juga dapat melakukan hal-hal yang lebih menakutkan, seperti membalikkan perahu yang berlayar di danau2. Jadi, Situ Gede bukan hanya sebuah danau biasa, melainkan juga tempat yang sarat dengan kisah-kisah mistis dan legenda di kalangan masyarakat Tasikmalaya"
        ),
        Mitos(
            id = 2,
            name = "Nyi Roro Kidul",
            img = R.drawable.nyi,
            desc = "Nyi Roro Kidul adalah sosok yang memikat dalam mitologi Jawa. Ia dipercayai sebagai Ratu Laut Selatan Jawa, memiliki kecantikan yang legendaris, dan menyimpan banyak misteri di kalangan penduduk pesisir selatan Pulau Jawa. Asal Usul Legenda Nyi Roro Kidul: Teosofi: Dalam perspektif teosofi, Nyi Roro Kidul dianggap tidak nyata. Geoffrey Hodson, seorang ahli teosofi, menyatakan bahwa keberadaannya hanya dalam ranah mistis. Agama Islam: Menurut pandangan Islam, Nyi Roro Kidul adalah sosok jin yang memiliki tingkatan tinggi. Ia bisa berubah bentuk dan dianggap sebagai bentuk bangsa jin. Kehadirannya membawa keberuntungan, keselamatan, dan rejeki1. Tempat Komunikasi: Beberapa tempat di Jawa dipercayai sebagai tempat komunikasi dengan Nyi Roro Kidul, termasuk Pantai Parangtritis, Pantai Parangkusumo, Pelabuhan Ratu, Samudera Beach Hotel, dan Pantai Pangandaran. Di hampir semua gambaran Nyi Roro Kidul, ia digambarkan sebagai seorang perempuan cantik yang mengenakan pakaian serba hijau. Meskipun demikian, kebenaran cerita rakyat ini masih menjadi pertanyaan. Beberapa menganggapnya sebagai putri duyung dengan ekor setengah ikan, sementara yang lain melihatnya sebagai putri yang mengendarai kereta kencana berkuda. Pantai Pangandaran juga memiliki tempat misterius yang dikaitkan dengan Nyi Roro Kidul, seperti Gua Panggung yang merupakan makam anak angkat sang ratu, Embah Jaga Lautan."
        ),
        Mitos(
            id = 3,
            name = "Jembatan Cirahong",
            img = R.drawable.cirahong,
            desc = "Jembatan Cirahong, yang terletak di antara Kabupaten Tasikmalaya dan Kabupaten Ciamis di Jawa Barat, Indonesia, adalah sebuah struktur bersejarah yang memiliki cerita mistis dan sejarah yang kaya. Berikut adalah detail mengenai misteri, mitos, dan sejarah jembatan tersebut: Sejarah Jembatan Cirahong: Jembatan Cirahong dibangun pada tahun 1893 oleh pemerintah Hindia Belanda. Ini adalah jembatan double decker atau geladak ganda yang unik, di mana bagian atas digunakan untuk jalur kereta api dan bagian bawah untuk lalu lintas kendaraan. Jembatan ini memiliki panjang 202 meter dan berada di ketinggian 66 meter di atas Sungai Citanduy. Pada tahun 1934, jembatan ini diperkuat sebagai bagian dari upaya pemerintah kolonial Belanda untuk mempercepat distribusi hasil bumi dan perkebunan ke Pelabuhan Cilacap. Mitos dan Misteri: Terdapat cerita mistis tentang sepasang pengantin yang dikubur hidup-hidup di beton penyangga jembatan sebagai tumbal. Kisah lain menyebutkan bahwa ada pekerja yang mengalami kecelakaan kerja dan tertimbun dalam pondasi beton saat pembangunan. Jembatan ini juga dikaitkan dengan penampakan bayangan mobil, suara tangisan, dan percobaan bunuh diri. Meskipun banyak mitos yang beredar, warga setempat banyak yang tidak mempercayai cerita-cerita tersebut dan menganggapnya sebagai bagian dari folklore lokal. Jembatan Cirahong juga telah menjadi destinasi wisata, menarik banyak pengunjung yang ingin menikmati pemandangan dan mengabadikan momen dengan berfoto di jembatan bersejarah ini."
        ),
        Mitos(
            id = 4,
            name = "Situ Sanghyang",
            img = R.drawable.sanghyang,
            desc = "Sejarah dan Lokasi Situ Sanghyang Situ Sanghyang adalah sebuah danau atau situ yang berada di Desa Cilolohan, Kecamatan Tanjungjaya, Kabupaten Tasikmalaya, Jawa Barat. Situ Sanghyang berlokasi di Jalan Raya Cibalanarik-Cilolohan dan menjadi salah satu destinasi wisata yang populer di wilayah Tasikmalaya dan sekitarnya. Situ Sanghyang dilengkapi dengan berbagai fasilitas seperti gazebo, musala, area bermain anak, dan penyewaan sepeda air. Misteri dan Mitos Situ Sanghyang Berikut adalah beberapa misteri dan mitos yang terkait dengan Situ Sanghyang: Asal Usul Situ Sanghyang: Sampai saat ini, sejarah dan asal usul Situ Sanghyang masih menjadi misteri. Menurut legenda yang beredar di masyarakat, nama Situ Sanghyang berasal dari sebuah peristiwa sejarah yaitu riuhnya suara yang saling bersahutan. Situ Sanghyang sendiri merupakan gabungan dua tempat bersejarah antara situ yang berada di Kampung Parunggolong dan Sanghyang di objek wisata. Mitos Sanghyang Sirah: Ada mitos yang beredar bahwa Situ Sanghyang adalah tempat pernikahan para raja. Menurut cerita yang diadopsi oleh Dinas Pariwisata, sebelum terjadinya nama situ, terlebih dahulu muncul nama sanghyang, karena menurut sejarah situ yang asli ada di Kampung Parunggolong Desa Cilolohan, berupa leuwi (sungai) bernama leuwi Sanghyang. Mitos Keberadaan Makhluk Gaib: Banyak masyarakat yang percaya bahwa Situ Sanghyang dihuni oleh makhluk gaib. Menurut cerita, siapa pun yang meminum air yang menenggelamkan Saung Satang akan berubah menjadi ikan. Situ Sanghyang sebagai Tempat Wisata Situ Sanghyang menjadi salah satu destinasi wisata di Tasikmalaya yang banyak dikunjungi saat liburan tiba. Keindahan alamnya yang masih terjaga menjadi daya tarik utama bagi pengunjung. Wisata ini banyak dikunjungi oleh berbagai kalangan, mulai dari dewasa hingga anak-anak. Selain itu, nilai-nilai historis dan mitos yang melekat pada Situ Sanghyang juga menjadi daya tarik tersendiri bagi para pengunjung."
        ),
        Mitos(
            id = 5,
            name = "Gunung Galunggung",
            img = R.drawable.galunggung,
            desc = "Sejarah dan Letusan Gunung Galunggung Gunung Galunggung, yang terletak sekitar 17 km dari pusat Kota Tasikmalaya, adalah gunung berapi dengan ketinggian 2.167 meter di atas permukaan laut. Gunung ini dikenal baik secara regional maupun internasional karena letusan dahsyatnya. Menurut catatan sejarah, Gunung Galunggung telah meletus sebanyak empat kali, yaitu pada tahun 1822, 1894, 1918, dan terakhir pada tahun 1982. Letusan pertama pada tahun 1822 menghasilkan awan panas, abu halus, hujan pasir kemerahan yang sangat panas, serta lahar panas. Letusan ini menghancurkan 114 desa dan menewaskan 4.011 jiwa. Letusan berikutnya pada tahun 1894 menghancurkan 50 desa yang terdapat di kaki gunung. Letusan terakhir pada tahun 1982 berlangsung selama sembilan bulan dan memiliki dampak yang sangat luas. Misteri dan Mitos Gunung Galunggung Gunung Galunggung juga dikenal dengan berbagai misteri dan mitos yang telah ada sejak zaman dahulu. Berikut adalah beberapa misteri dan mitos yang terkait dengan Gunung Galunggung: Mitos Fotografi: Menurut mitos yang populer di kalangan fotografer, keindahan Gunung Galunggung tidak bisa diabadikan lewat kamera. Banyak fotografer yang telah mencoba memotret gunung ini, namun hasilnya selalu sama: keindahan Gunung Galunggung seakan lenyap saat difoto. Misteri Sumber Mata Air 7 Rasa: Di Gunung Galunggung dikatakan terdapat 7 sumber mata air yang mengeluarkan air dengan masing-masing rasa yang berbeda. Misteri Pemukiman Bangsa Jin: Dipercaya bahwa puncak Gunung Galunggung adalah tempat permukiman mahluk ghaib sebangsa jin. Misteri Pelet Gunung Galunggung: Konon, gunung ini memiliki sebuah pelet magis yang dapat membuat orang ingin kembali ke gunung ini. Jika Anda pernah mendatangi Gunung Galunggung, suatu saat Anda akan merasa ingin kembali ke gunung ini. Misteri Hantu Penghuni Gunung: Banyak cerita yang beredar di masyarakat tentang hantu-hantu penghuni gunung ini. Mereka seringkali berlarian sambil menangis. Mungkin mereka adalah hantu-hantu khodam para korban letusan gunung Galunggung. Gunung Galunggung sebagai Tempat Wisata Selain dikenal dengan misteri dan mitosnya, Gunung Galunggung juga merupakan tempat tujuan wisata yang populer. Gunung ini memiliki daya tarik wisata yang tinggi dan sering dikunjungi oleh wisatawan lokal bahkan sampai mancanegara. Untuk mencapai puncak Galunggung, dibangun sebuah tangga yang memiliki panjang 620 anak tangga. Gunung Galunggung memiliki dua puncak yaitu Puncak Dinding Ari dan Puncak Beuti Canar, kedua puncak tersebut dapat dijangkau dengan cara mendaki melalui jalur yang tersedia."
        ),
        Mitos(
            id = 6,
            name = "Batu Goong",
            img = R.drawable.goong,
            desc = "Batu Goong di Desa Bangbayang, Kecamatan Cipaku, Kabupaten Ciamis, memiliki cerita menarik yang dikelilingi oleh aura magis dan keberuntungan. Batu ini merupakan batuan andesit alami berbentuk persegi panjang sedikit opal dengan lingkar sisinya sekitar 366 sentimeter dan tebal 44 sentimeter. Dinamakan “Batu Goong” karena bentuknya menyerupai alat musik gamelan Goong. Pada bagian permukaannya, terdapat tonjolan membulat dengan ukuran panjang 30 sentimeter dan lebar 28 sentimeter, dengan tinggi tonjokan sekitar 10 sentimeter. Konon, pada malam Jumat Kliwon, Batu Goong ini bahkan berbunyi, dan warga sering mendengar suara gamelan yang berasal dari lokasi batu ini. Selain itu, Batu Goong juga dipercaya dapat mendatangkan keberuntungan. Pada masa lalu, orang-orang yang ingin mendapatkan keuntungan dari acara seperti pekan olahraga dan ketangkasan (porkas) datang ke Batu Goong ini. Meskipun zaman telah berubah, dan acara seperti porkas tidak lagi ada, Batu Goong tetap menjadi bagian dari sejarah Desa Bangbayang dan memiliki daya tarik mistis yang menarik perhatian banyak orang."
        ),
        Mitos(
            id = 7,
            name = "Tanjakan Panganten",
            img = R.drawable.tanjakan_panganten,
            desc = "Tanjakan Panganten di Garut adalah tempat yang melegenda dan memiliki aura mistis. Terletak di Jalan Raya Pakenjeng-Pamulihan, tanjakan ini memiliki medan yang curam dengan tingkat kemiringan sekitar 45 derajat. Jalannya memanjang sekitar 700 meter dan terletak di sebuah tebing yang menambah suasana seram dan ekstrem. Nama “Panganten” diambil dari kisah tragis yang melibatkan pengantin baru yang melintas di tanjakan ini. Mitos yang paling populer menyatakan bahwa agar selamat dari tanjakan Panganten, rombongan pengantin pria harus turun dari mobil, berjalan kaki melintasi tanjakan, dan hanya kemudian dapat kembali ke kendaraan di bawah tanjakan. Ada juga cerita tentang seorang wanita yang akan dinikahi oleh lelaki dari luar Garut. Sayangnya, kendaraan sang mempelai lelaki jatuh ke dalam jurang di tanjakan Panganten hingga meninggal dunia dan menewaskan hampir semua rombongan. Wanita itu sendiri ditemukan meninggal akibat depresi dan bunuh diri. Tanjakan Panganten menjadi tempat yang sarat dengan cerita misteri dan tragedi, terutama yang melibatkan pengantin. Meskipun terdapat mitos dan kepercayaan lokal, tetaplah waspada saat melewati tanjakan ini. Siapa sangka, di balik medannya yang curam, tersembunyi kisah-kisah yang menggugah perasaan dan memperkuat legenda mistisnya."
        ),
        Mitos(
            id = 8,
            name = "Leuweung Sancang",
            img = R.drawable.sancang,
            desc = "Leuweung Sancang, yang terletak di Kabupaten Garut, Jawa Barat, merupakan hutan yang sarat dengan misteri dan nuansa mistis. Secara harfiah, kata “leuweung” dalam bahasa Sunda berarti hutan, sehingga Leuweung Sancang dapat diartikan sebagai Hutan Sancang. Hutan ini memiliki luas sekitar 2.157 hektar dan terdiri dari hutan dataran rendah, hutan mangrove, dan hutan pantai. Cuaca di tempat ini berkisar antara 17 hingga 28 derajat Celsius. Bagi masyarakat Sunda, tempat ini bukanlah hal yang asing karena telah menjadi legenda sebagai lokasi menghilangnya Raja Pajajaran, Prabu Siliwangi. Prabu Siliwangi adalah seorang raja yang memerintah di kerajaan Pajajaran, yang memiliki dasar kepercayaan Hindu terbesar di Jawa Barat. Ia dikenal sebagai sosok bijaksana dan memiliki seorang istri bernama Dewi Kumalawangi. Pasangan ini memiliki tiga anak: Dewi Rara Santang, Raden Walangsungsan, dan Raden Kian Santang. Leuweung Sancang memiliki kaitan dengan Prabu Siliwangi, tokoh legendaris dalam sejarah Sunda. Berdasarkan kepercayaan masyarakat, Hutan Sancang merupakan tempat terakhir Prabu Siliwangi ketika melakukan ngahiang (mengundurkan diri) atau melakukan moksa (penyatuan dengan Tuhan). Di sini, Prabu Siliwangi menimba ilmu kedidayaan dan memperdalam ilmu kesaktian tanpa brata. Leuweung Sancang menjadi tempat yang konon menjadi tempat Prabu Siliwangi menghilang ketika dikerjar oleh putranya yang mengajaknya untuk memeluk agama Islam. Oleh karena itu, tempat ini sering digunakan sebagai lokasi untuk meminta ilmu kanuragan atau kebal. Beberapa cerita horor juga beredar tentang Leuweung Sancang, termasuk pengamatan tentang suara aneh dan kehadiran harimau dengan warna yang berbeda. Selain itu, Leuweung Sancang juga memiliki keberagaman flora dan fauna yang menakjubkan. Beberapa fauna yang ditemukan di sini meliputi merak, sapi liar, owa jawa, kijang, ajag, dan macan. Namun, yang paling terkenal adalah banteng liar Sancang. Sayangnya, populasi banteng Sancang saat ini telah punah. Adapun flora di hutan ini mencakup pohon palahlar, werejit, dan spesies baru pohon meranti yang ditemukan oleh ahli botani Kostermans pada tahun 1983. Dengan segala potensinya, Leuweung Sancang telah ditetapkan sebagai kawasan konservasi oleh pemerintah sejak tahun 1959. Status cagar alamnya juga diberikan pada tahun 1978. Hutan ini memang menyimpan banyak misteri dan keajaiban alam yang patut dijaga dan dihormati. Hutan ini dilindungi oleh dua makhluk: manusia sebagai penjaga dan makhluk gaib. Konon, aura mistis mengelilingi Leuweung Sancang, dan banyak orang melaporkan pengalaman aneh saat berada di sana. Meskipun terkadang dianggap angker, hutan ini juga memiliki pantai dengan pasir putih yang menawan. Di dalamnya terdapat pohon yang katanya menjadi tempat Prabu Siliwangi menghilang dan akan kembali. Mitos dan cerita seputar Leuweung Sancang ini tetap memikat perhatian dan menjadi bagian dari warisan budaya dan sejarah Jawa Barat."
        ),
        Mitos(
            id = 9,
            name = "Situ Lengkong Panjalu",
            img = R.drawable.situ_lengkong,
            desc = "Situ Lengkong Panjalu, yang terletak di Desa Panjalu, Kecamatan Panjalu, Kabupaten Ciamis, Jawa Barat, adalah sebuah danau yang kaya akan sejarah dan mitos. Dengan luas sekitar 67,2 hektar dan terletak pada ketinggian 700 meter di atas permukaan laut, danau ini memiliki pulau kecil di tengahnya yang dikenal sebagai Nusa Larang atau Nusa Gede. Sejarah Situ Lengkong Panjalu: Menurut cerita rakyat yang diwariskan turun-temurun dan Babad Panjalu, Situ Lengkong Panjalu adalah ‘danau buatan’ yang tercipta dari usaha manusia. Kisahnya bermula ketika Sanghyang Borosngora, putra Raja Panjalu Prabu Cakradewa, kembali dari Tanah Suci Mekah dengan membawa air zamzam. Air tersebut dikucurkan ke lembah yang mengelilingi bukit Pasir Jambu, yang kemudian berubah menjadi danau, sementara bukit tersebut menjadi Nusa Larang. Mitos Situ Lengkong Panjalu: Beberapa mitos yang berkaitan dengan Situ Lengkong Panjalu antara lain keberadaan naga besar yang dianggap sebagai penjaga danau. Selain itu, ada cerita tentang sepasang harimau jadi-jadian yang dianggap sebagai cucu dari Prabu Siliwangi, yang bertugas menjaga kelestarian alam di wilayah tersebut. Situ Lengkong Panjalu juga merupakan tempat yang memiliki nilai religi, dengan adanya makam keramat di pulau Nusa Larang, yang diduga kuat merupakan makam salah satu Raja Panjalu yang juga penyebar Agama Islam. Pada tanggal 21 Februari 2019, Situ Lengkong Panjalu ditetapkan sebagai kawasan cagar alam, menandakan pentingnya tempat ini dalam sejarah lokal.Danau ini tidak hanya menarik bagi mereka yang tertarik dengan sejarah dan mitos, tetapi juga bagi pengunjung yang mencari keindahan alam dan ketenangan. Fasilitas yang tersedia di Situ Lengkong Panjalu meliputi area parkir, toilet, mushola, warung oleh-oleh, perahu, dan kawasan cagar alam, membuatnya menjadi destinasi yang sempurna untuk berbagai aktivitas wisata."
        ),
        Mitos(
            id = 10,
            name = "Situ Bojongmengger",
            img = R.drawable.bojongmengger,
            desc = "Situ Bojongmengger terletak di Desa Bojongmengger, Kecamatan Cijeungjing, Kabupaten Ciamis, Jawa Barat. Sebelum menjadi waduk, lokasi ini adalah sebuah leuwi atau danau alami. Waduk ini memiliki kedalaman 2-3 meter dan luasnya diperkirakan 4-5 hektar. Waduk ini memiliki mata air sendiri, sehingga tidak pernah surut meski pada musim kemarau. Misteri dan Mitos Situ Bojongmengger Mitos Siluman Ikan Gabus: Ada cerita mistis dan mitos di Situ Bojongmengger yang mengatakan bahwa area ini dihuni oleh makhluk halus yang menyerupai penampakan ikan gabus raksasa. Warga sekitar menyebutnya Abah Bapang Bogo. Ikan siluman ini dikatakan memiliki ukuran seperti anak usia lima tahun, padahal umumnya ikan gabus tidak sebesar itu. Larangan dan Tata Tertib: Ada beberapa larangan dan tata tertib saat orang berada di Situ Bojongmengger. Orang dilarang berteriak di area situ dan tidak boleh berisik, termasuk memicu keramaian. Pelanggaran terhadap larangan ini dipercaya bisa memicu kemunculan ikan siluman. Situ Bojongmengger sebagai Tempat Wisata. Situ Bojongmengger menjadi salah satu destinasi wisata di Ciamis. Keindahan alam dan panorama waduk ini membuat tempat ini hampir tak pernah sepi pengunjung, terlebih lagi saat hari libur. Selain itu, waduk ini juga dimanfaatkan sebagai sarana perikanan darat dan sumber air bersih. Situ Bojongmengger di Ciamis memiliki sejarah dan mitos yang menarik. Dari mitos tentang siluman ikan gabus hingga larangan dan tata tertib yang harus diikuti, semua menambah nuansa mistis pada waduk ini. Namun, di balik mitos dan misterinya, Situ Bojongmengger juga menjadi tempat wisata yang populer dengan pemandangan alam yang indah dan berbagai fasilitas menarik yang bisa dinikmati oleh pengunjung."
        )
    )
}